import { cp, mkdtemp, mkdir, readFile, readdir, rm, unlink, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { basename, dirname, join, resolve } from 'node:path';
import { spawnSync } from 'node:child_process';
import { sha256Hex } from '@pp/artifacts';
import { createDiagnostic, fail, ok, type OperationResult } from '@pp/diagnostics';
import type { CanvasBuildResult, CanvasControlDefinition, CanvasSourceModel, CanvasTemplateRequirementResolution } from './index';
import { buildCanvasTemplateSurface } from './template-surface';

interface GeneratedControlInfoFile {
  TopParent: GeneratedControlInfo;
}

interface GeneratedControlInfo {
  Type: 'ControlInfo';
  Name: string;
  HasDynamicProperties?: boolean;
  Template: GeneratedTemplateRef;
  Index: number;
  PublishOrderIndex: number;
  VariantName: string;
  LayoutName: string;
  MetaDataIDKey: string;
  PersistMetaDataIDKey: boolean;
  IsFromScreenLayout: boolean;
  StyleName: string;
  Parent: string;
  IsDataControl: boolean;
  AllowAccessToGlobals: boolean;
  OptimizeForDevices: string;
  IsGroupControl: boolean;
  IsAutoGenerated: boolean;
  IsLocked: boolean;
  ControlUniqueId: string;
  Rules: GeneratedRule[];
  ControlPropertyState: Array<string | GeneratedPropertyState>;
  Children: GeneratedControlInfo[];
}

interface GeneratedTemplateRef {
  Id: string;
  Version: string;
  LastModifiedTimestamp: string;
  Name: string;
  FirstParty: boolean;
  IsPremiumPcfControl: boolean;
  IsCustomGroupControlTemplate: boolean;
  CustomGroupControlTemplateName: string;
  IsComponentDefinition: boolean;
  OverridableProperties: Record<string, unknown>;
}

interface GeneratedRule {
  Property: string;
  Category: string;
  InvariantScript: string;
  RuleProviderType: string;
}

interface GeneratedPropertyState {
  InvariantPropertyName: string;
  AutoRuleBindingEnabled: boolean;
  AutoRuleBindingString: string;
  NameMapSourceSchema: string;
  IsLockable: boolean;
  AFDDataSourceName: string;
}

export async function buildCanvasMsappFromUnpackedSource(
  source: CanvasSourceModel,
  requirements: CanvasTemplateRequirementResolution,
  outPath: string
): Promise<OperationResult<CanvasBuildResult>> {
  if (source.kind !== 'pa-yaml-unpacked') {
    return fail(
      createDiagnostic('error', 'CANVAS_NATIVE_BUILD_SOURCE_KIND_INVALID', 'Native .msapp build only supports unpacked .pa.yaml canvas sources.', {
        source: '@pp/canvas',
      })
    );
  }

  if (!source.unpackedArtifacts?.headerPath || !source.unpackedArtifacts?.propertiesPath || !source.unpackedArtifacts?.appControlPath) {
    return fail(
      createDiagnostic(
        'error',
        'CANVAS_NATIVE_BUILD_BASELINE_REQUIRED',
        `Canvas source ${source.root} is missing the baseline unpacked app artifacts required for native .msapp build.`,
        {
          source: '@pp/canvas',
          hint: 'Build from an unpacked app root that still contains Header.json, Properties.json, and Controls/1.json.',
        }
      )
    );
  }

  const tempRoot = await mkdtemp(join(tmpdir(), 'pp-canvas-build-'));

  try {
    await cp(source.root, tempRoot, { recursive: true });
    await mkdir(dirname(outPath), { recursive: true });

    const controlsDir = join(tempRoot, 'Controls');
    const templatesPath = join(tempRoot, 'References', 'Templates.json');
    const editorStatePath = join(tempRoot, 'Src', '_EditorState.pa.yaml');
    const headerPath = join(tempRoot, 'Header.json');
    const screenControlFiles = await resolveScreenControlFileNames(source.root, source.screens.map((screen) => screen.name));
    const generatedScreens = generateScreenControlFiles(source, requirements, screenControlFiles);

    await removeExistingScreenControlFiles(controlsDir);

    for (const [fileName, document] of generatedScreens.entries()) {
      await writeFile(join(controlsDir, fileName), `${JSON.stringify(document, null, 2)}\n`, 'utf8');
    }

    await writeFile(templatesPath, `${JSON.stringify(buildUsedTemplatesDocument(requirements), null, 2)}\n`, 'utf8');
    await writeFile(editorStatePath, renderEditorStateYaml(source.screens.map((screen) => screen.name)), 'utf8');
    await updateHeaderTimestamp(headerPath);

    const zipResult = spawnSync('zip', ['-rqX', outPath, '.'], {
      cwd: tempRoot,
      encoding: 'utf8',
    });

    if (zipResult.status !== 0) {
      return fail(
        createDiagnostic('error', 'CANVAS_NATIVE_BUILD_ZIP_FAILED', `Failed to package ${outPath} as an .msapp archive.`, {
          source: '@pp/canvas',
          detail: (zipResult.stderr || zipResult.stdout).trim() || '<no output>',
        })
      );
    }

    const resolvedTemplates = requirements.resolutions
      .filter((resolution): resolution is typeof resolution & { template: NonNullable<typeof resolution.template> } => Boolean(resolution.template))
      .map((resolution) => resolution.template);
    const packageHash = await hashCanvasPackageDirectory(tempRoot);

    return ok(
      {
        outPath,
        mode: requirements.mode,
        sourceHash: source.sourceHash,
        templateHash: sha256Hex(JSON.stringify(resolvedTemplates.map((template) => template.contentHash))),
        packageHash,
        supported: true,
      },
      {
        supportTier: 'preview',
      }
    );
  } finally {
    await rm(tempRoot, { recursive: true, force: true });
  }
}

function generateScreenControlFiles(
  source: CanvasSourceModel,
  requirements: CanvasTemplateRequirementResolution,
  screenControlFiles: Map<string, string>
): Map<string, GeneratedControlInfoFile> {
  const generated = new Map<string, GeneratedControlInfoFile>();
  const resolutionMap = new Map(
    requirements.resolutions.map((resolution) => [`${resolution.requested.name}@${resolution.requested.version ?? ''}`, resolution])
  );
  let nextId = 4;

  for (const screen of source.screens) {
    const topParent = generateScreenControl(screen.name, screen.properties ?? {}, nextId);
    nextId += 1;

    topParent.Children = screen.controls.map((control, index) =>
      generateControlInfo(control, screen.name, index, resolutionMap, () => String(nextId++))
    );

    generated.set(screenControlFiles.get(screen.name) ?? `${generated.size + 4}.json`, {
      TopParent: topParent,
    });
  }

  return generated;
}

function generateScreenControl(
  screenName: string,
  properties: Record<string, unknown>,
  controlUniqueId: number
): GeneratedControlInfo {
  const defaults = new Map<string, { value: string; category: string }>([
    ['Fill', { value: 'Color.White', category: 'Design' }],
    ['ImagePosition', { value: 'ImagePosition.Fit', category: 'Design' }],
    ['Height', { value: 'Max(App.Height, App.MinScreenHeight)', category: 'Design' }],
    ['Width', { value: 'Max(App.Width, App.MinScreenWidth)', category: 'Design' }],
    ['Size', { value: '1 + CountRows(App.SizeBreakpoints) - CountIf(App.SizeBreakpoints, Value >= Self.Width)', category: 'Design' }],
    ['Orientation', { value: 'If(Self.Width < Self.Height, Layout.Vertical, Layout.Horizontal)', category: 'Design' }],
    ['LoadingSpinner', { value: 'LoadingSpinner.None', category: 'Design' }],
    ['LoadingSpinnerColor', { value: 'RGBA(56, 96, 178, 1)', category: 'Design' }],
  ]);

  for (const [property, value] of Object.entries(properties)) {
    defaults.set(property, {
      value: toInvariantScript(value),
      category: inferPropertyCategory(property, undefined),
    });
  }

  const rules = Array.from(defaults.entries()).map(([property, value]) => ({
    Property: property,
    Category: value.category,
    InvariantScript: value.value,
    RuleProviderType: 'Unknown',
  }));

  return {
    Type: 'ControlInfo',
    Name: screenName,
    Template: {
      Id: 'http://microsoft.com/appmagic/screen',
      Version: '1.0',
      LastModifiedTimestamp: '0',
      Name: 'screen',
      FirstParty: true,
      IsPremiumPcfControl: false,
      IsCustomGroupControlTemplate: false,
      CustomGroupControlTemplateName: '',
      IsComponentDefinition: false,
      OverridableProperties: {},
    },
    Index: 0,
    PublishOrderIndex: 0,
    VariantName: '',
    LayoutName: '',
    MetaDataIDKey: '',
    PersistMetaDataIDKey: false,
    IsFromScreenLayout: false,
    StyleName: 'defaultScreenStyle',
    Parent: '',
    IsDataControl: false,
    AllowAccessToGlobals: true,
    OptimizeForDevices: 'Off',
    IsGroupControl: false,
    IsAutoGenerated: false,
    IsLocked: false,
    ControlUniqueId: String(controlUniqueId),
    Rules: rules,
    ControlPropertyState: rules.map((rule) =>
      Object.prototype.hasOwnProperty.call(properties, rule.Property)
        ? {
            InvariantPropertyName: rule.Property,
            AutoRuleBindingEnabled: false,
            AutoRuleBindingString: '',
            NameMapSourceSchema: '?',
            IsLockable: false,
            AFDDataSourceName: '',
          }
        : rule.Property
    ),
    Children: [],
  };
}

function generateControlInfo(
  control: CanvasControlDefinition,
  parentName: string,
  publishOrderIndex: number,
  resolutions: Map<string, CanvasTemplateRequirementResolution['resolutions'][number]>,
  allocateId: () => string
): GeneratedControlInfo {
  const resolution = resolutions.get(`${control.templateName}@${control.templateVersion}`);

  if (!resolution?.template) {
    throw new Error(`Missing resolved template for ${control.templateName}@${control.templateVersion}.`);
  }

  const surface = buildCanvasTemplateSurface(resolution.template);
  const templateName = surface.runtimeName ?? resolution.template.templateName;
  const defaults = new Map<string, { value: string; category: string }>(
    Object.entries(surface.defaultProperties).map(([property, value]) => [
      property,
      {
        value,
        category: inferPropertyCategory(property, surface.propertyCategories[property]),
      },
    ])
  );

  for (const [property, value] of Object.entries(control.properties)) {
    defaults.set(property, {
      value: toInvariantScript(value),
      category: inferPropertyCategory(property, surface.propertyCategories[property]),
    });
  }

  if (!defaults.has('ZIndex')) {
    defaults.set('ZIndex', {
      value: String(publishOrderIndex + 1),
      category: 'Design',
    });
  }

  const rules = Array.from(defaults.entries()).map(([property, value]) => ({
    Property: property,
    Category: value.category,
    InvariantScript: value.value,
    RuleProviderType: 'Unknown',
  }));
  const info: GeneratedControlInfo = {
    Type: 'ControlInfo',
    Name: control.name,
    HasDynamicProperties: false,
    Template: {
      Id: surface.templateId ?? `http://microsoft.com/appmagic/${templateName.toLowerCase()}`,
      Version: resolution.template.templateVersion,
      LastModifiedTimestamp: '0',
      Name: templateName,
      FirstParty: surface.firstParty,
      IsPremiumPcfControl: surface.isPremiumPcfControl,
      IsCustomGroupControlTemplate: false,
      CustomGroupControlTemplateName: '',
      IsComponentDefinition: surface.isComponentDefinition,
      OverridableProperties: {},
    },
    Index: 0,
    PublishOrderIndex: publishOrderIndex,
    VariantName: control.variantName ?? '',
    LayoutName: control.layoutName ?? '',
    MetaDataIDKey: '',
    PersistMetaDataIDKey: false,
    IsFromScreenLayout: false,
    StyleName: surface.styleName ?? 'defaultControlStyle',
    Parent: parentName,
    IsDataControl: false,
    AllowAccessToGlobals: true,
    OptimizeForDevices: 'Off',
    IsGroupControl: false,
    IsAutoGenerated: false,
    IsLocked: false,
    ControlUniqueId: allocateId(),
    Rules: rules,
    ControlPropertyState: rules.map((rule) =>
      Object.prototype.hasOwnProperty.call(control.properties, rule.Property)
        ? {
            InvariantPropertyName: rule.Property,
            AutoRuleBindingEnabled: false,
            AutoRuleBindingString: '',
            NameMapSourceSchema: '?',
            IsLockable: false,
            AFDDataSourceName: '',
          }
        : rule.Property
    ),
    Children: [],
  };

  info.Children = control.children.map((child, index) =>
    generateControlInfo(child, control.name, index, resolutions, allocateId)
  );

  return info;
}

async function resolveScreenControlFileNames(root: string, screenNames: string[]): Promise<Map<string, string>> {
  const controlsDir = join(root, 'Controls');
  const entries = await readdir(controlsDir, { withFileTypes: true }).catch(() => []);
  const existing = new Map<string, string>();
  const used = new Set<string>();
  let nextFileNumber = 4;

  for (const entry of entries) {
    if (!entry.isFile() || !entry.name.endsWith('.json') || entry.name === '1.json') {
      continue;
    }

    const controlFile = await readControlFile(join(controlsDir, entry.name));
    const topParent = asRecord(controlFile?.TopParent);
    const topParentName = typeof topParent?.Name === 'string' ? topParent.Name : undefined;

    if (topParentName) {
      existing.set(topParentName, entry.name);
      used.add(entry.name);
    }

    const numericPrefix = Number.parseInt(entry.name.replace(/\.json$/i, ''), 10);

    if (!Number.isNaN(numericPrefix)) {
      nextFileNumber = Math.max(nextFileNumber, numericPrefix + 1);
    }
  }

  const resolved = new Map<string, string>();

  for (const screenName of screenNames) {
    const fileName = existing.get(screenName);

    if (fileName) {
      resolved.set(screenName, fileName);
      continue;
    }

    let candidate = `${nextFileNumber}.json`;

    while (used.has(candidate)) {
      nextFileNumber += 1;
      candidate = `${nextFileNumber}.json`;
    }

    used.add(candidate);
    resolved.set(screenName, candidate);
    nextFileNumber += 1;
  }

  return resolved;
}

async function removeExistingScreenControlFiles(controlsDir: string): Promise<void> {
  const entries = await readdir(controlsDir, { withFileTypes: true });

  for (const entry of entries) {
    if (!entry.isFile() || !entry.name.endsWith('.json') || entry.name === '1.json') {
      continue;
    }

    await unlink(join(controlsDir, entry.name));
  }
}

async function readControlFile(path: string): Promise<Record<string, unknown> | undefined> {
  try {
    return JSON.parse(await readFile(path, 'utf8')) as Record<string, unknown>;
  } catch {
    return undefined;
  }
}

function asRecord(value: unknown): Record<string, unknown> | undefined {
  return typeof value === 'object' && value !== null && !Array.isArray(value)
    ? (value as Record<string, unknown>)
    : undefined;
}

function buildUsedTemplatesDocument(requirements: CanvasTemplateRequirementResolution) {
  return {
    UsedTemplates: requirements.resolutions
      .filter((resolution): resolution is typeof resolution & { template: NonNullable<typeof resolution.template> } => Boolean(resolution.template))
      .map((resolution) => ({
        Name: resolution.template.templateName,
        Version: resolution.template.templateVersion,
        Template: readTemplateXml(resolution.template),
      })),
  };
}

function renderEditorStateYaml(screenNames: string[]): string {
  const lines = [
    '# ************************************************************************************************',
    '# Warning: YAML source code for Canvas Apps should only be used to review changes made within Power Apps Studio and for minor edits (Preview).',
    '# Use the maker portal to create and edit your Power Apps.',
    '# ',
    '# The schema file for Canvas Apps is available at https://go.microsoft.com/fwlink/?linkid=2304907',
    '# ',
    '# For more information, visit https://go.microsoft.com/fwlink/?linkid=2292623',
    '# ************************************************************************************************',
    'EditorState:',
    '  ScreensOrder:',
    ...screenNames.map((screenName) => `    - ${screenName}`),
    '',
  ];

  return lines.join('\n');
}

async function updateHeaderTimestamp(path: string): Promise<void> {
  const header = JSON.parse(await readFile(path, 'utf8')) as Record<string, unknown>;
  header.LastSavedDateTimeUTC = new Date().toLocaleString('en-US', {
    hour12: false,
    month: '2-digit',
    day: '2-digit',
    year: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
    second: '2-digit',
    timeZone: 'UTC',
  }).replace(',', '');
  await writeFile(path, `${JSON.stringify(header, null, 2)}\n`, 'utf8');
}

async function hashCanvasPackageDirectory(root: string): Promise<string> {
  const files = await listFiles(root);
  const entries = await Promise.all(
    files.map(async (path) => {
      const relativePath = path.slice(root.length + 1).replaceAll('\\', '/');
      const bytes = await readFile(path);

      if (relativePath === 'Header.json') {
        const header = JSON.parse(bytes.toString('utf8')) as Record<string, unknown>;
        if (typeof header.LastSavedDateTimeUTC === 'string') {
          header.LastSavedDateTimeUTC = '<LAST_SAVED_DATE_TIME_UTC>';
        }

        return {
          path: relativePath,
          content: JSON.stringify(header),
        };
      }

      return {
        path: relativePath,
        content: bytes.toString('base64'),
      };
    })
  );

  entries.sort((left, right) => left.path.localeCompare(right.path));
  return sha256Hex(JSON.stringify(entries));
}

async function listFiles(root: string): Promise<string[]> {
  const entries = await readdir(root, { withFileTypes: true });
  const files: string[] = [];

  for (const entry of entries) {
    const path = join(root, entry.name);
    if (entry.isDirectory()) {
      files.push(...(await listFiles(path)));
      continue;
    }

    if (entry.isFile()) {
      files.push(path);
    }
  }

  return files;
}

function readTemplateXml(template: NonNullable<CanvasTemplateRequirementResolution['resolutions'][number]['template']>): string {
  const templatesJson = template.files?.['References/Templates.json'];

  if (!templatesJson || typeof templatesJson !== 'object' || Array.isArray(templatesJson)) {
    return '';
  }

  const templateXml = (templatesJson as Record<string, unknown>).templateXml;
  return typeof templateXml === 'string' ? templateXml : '';
}

function toInvariantScript(value: unknown): string {
  if (typeof value === 'string') {
    return value.startsWith('=') ? value.slice(1).trim() : value;
  }

  return String(value ?? '');
}

function inferPropertyCategory(property: string, category: string | undefined): string {
  if (category) {
    return category;
  }

  if (property.startsWith('On')) {
    return 'Behavior';
  }

  if (property === 'Text' || property === 'Items' || property === 'Image' || property === 'Default' || property === 'Value') {
    return 'Data';
  }

  return 'Design';
}
