export function printSolutionHelp(): void {
  process.stdout.write(
    [
      'Usage: solution <command> [options]',
      '',
      'Manage the remote application boundary inside a Dataverse environment.',
      '',
      'Remote commands:',
      '  create <uniqueName>         create a solution shell in an environment',
      '  delete <uniqueName>         delete one solution from an environment',
      '  set-metadata <uniqueName>   update solution publisher or version metadata',
      '  publish <uniqueName>        publish customizations and optionally wait for an export checkpoint',
      '  sync-status <uniqueName>    inspect publish readback and export readiness for one solution',
      '  checkpoint <uniqueName>     capture a rollback-ready export plus live solution inventory',
      '  list                        list solutions in an environment',
      '  publishers                  list available solution publishers in an environment',
      '  inspect <uniqueName>        inspect one solution',
      '  components <uniqueName>     list solution components',
      '  dependencies <uniqueName>   list solution dependencies',
      '  analyze <uniqueName>        render a normalized analysis view',
      '  compare [uniqueName]        compare source and target solution states',
      '  export <uniqueName>         export a solution package',
      '  import <path.zip>           import a solution package',
      '',
      'Local package commands:',
      '  pack <folder>               pack a local solution folder into a zip',
      '  unpack <path.zip>           unpack a solution zip into a folder',
      '',
      'How to think about it:',
      '  - Use remote commands when the solution already lives in Dataverse and you need inventory, metadata, or lifecycle operations.',
      '  - Use pack/unpack when you are moving between editable local source and packaged zip artifacts.',
      '  - `pp solution unpack ... --extract-canvas-apps` also expands each CanvasApps/*.msapp into normalized editable source inside the unpacked solution tree.',
      '  - `pp solution pack ... --rebuild-canvas-apps` rebuilds those extracted CanvasApps/* folders back into sibling .msapp files before zipping the solution.',
      '  - A solution is the ALM boundary that groups canvas apps, flows, model-driven apps, env vars, and connection references.',
      '',
      'Examples:',
      '  pp solution list --environment dev --format json',
      '  pp solution publishers --environment dev --format json',
      '  pp solution list --environment dev --prefix ppHarness --format json',
      '  pp solution inspect Core --environment dev',
      '',
      'Common output options:',
      '  --format table|json|yaml|ndjson|markdown|raw',
    ].join('\n') + '\n'
  );
}

export function printSolutionListHelp(): void { process.stdout.write(['Usage: solution list --environment ALIAS [--no-interactive-auth] [options]','','Behavior:','  - Lists installed solutions in the target environment across all Dataverse pages.','  - Returns structured records with solution ids, unique names, friendly names, versions, and managed state.','  - Use --prefix to narrow by unique/friendly name prefix or --unique-name for one exact solution.','','Choose this when:','  - You know the environment but not yet the exact solution boundary you need.','','Examples:','  pp solution list --environment dev','  pp solution list --environment dev --format json','  pp solution list --environment dev --no-interactive-auth --format json','  pp solution list --environment dev --prefix ppHarness20260310T200706248Z --format json','','Options:','  --prefix PREFIX            Match solution unique names or friendly names starting with PREFIX','  --unique-name NAME        Match one exact solution unique name','  --no-interactive-auth     Fail fast with structured diagnostics instead of opening browser auth','','Common output options:','  --format table|json|yaml|ndjson|markdown|raw',].join('\n') + '\n'); }

export function printSolutionPublishersHelp(): void { process.stdout.write(['Usage: solution publishers --environment ALIAS [--no-interactive-auth] [options]','','Behavior:','  - Lists available solution publishers in the target environment.','  - Returns structured records with publisher ids, unique names, and friendly names when available.','  - Gives solution creation a first-class discovery step instead of requiring raw Dataverse queries or existing-solution archaeology.','','Choose this when:','  - You need a valid `--publisher-id` or `--publisher-unique-name` before running `pp solution create` or `pp solution set-metadata`.','','Examples:','  pp solution publishers --environment dev','  pp solution publishers --environment dev --format json','  pp solution create Core --environment dev --publisher-unique-name DefaultPublisher','','Options:','  --no-interactive-auth     Fail fast with structured diagnostics instead of opening browser auth','','Common output options:','  --format table|json|yaml|ndjson|markdown|raw',].join('\n') + '\n'); }

export function printSolutionCreateHelp(): void { process.stdout.write(['Usage: solution create <uniqueName> --environment ALIAS [--friendly-name NAME] [--version X.Y.Z.W] [--description TEXT] (--publisher-id GUID | --publisher-unique-name NAME)','','Behavior:','  - Creates one unmanaged solution shell in the target environment.','  - Requires either a publisher id or publisher unique name so the new solution has an explicit publisher binding.','  - Use `pp solution publishers --environment <alias>` when you need to discover a valid publisher binding first.','  - `--help` only prints this text and never validates the solution name or environment flags.','','Choose this when:','  - You need a new ALM boundary in Dataverse before attaching apps, env vars, connection references, or solution-scoped metadata.','','Examples:','  pp solution create Core --environment dev --publisher-unique-name pp','  pp solution create Core --environment dev --friendly-name "Core" --version 1.0.0.0 --publisher-id 00000000-0000-0000-0000-000000000000','','Common output options:','  --format table|json|yaml|ndjson|markdown|raw',].join('\n') + '\n'); }

export function printSolutionSetMetadataHelp(): void { process.stdout.write(['Usage: solution set-metadata <uniqueName> --environment ALIAS [--version X.Y.Z.W] [--publisher-id GUID | --publisher-unique-name NAME]','','Behavior:','  - Updates publisher binding and/or version metadata for one existing solution.','  - Requires at least one of `--version`, `--publisher-id`, or `--publisher-unique-name`.','  - `--help` only prints this text and never validates the solution name or environment flags.','','Choose this when:','  - The solution already exists and you need to align versioning or publisher ownership before export, deploy, or app attachment.','','Examples:','  pp solution set-metadata Core --environment dev --version 2026.3.11.51035','  pp solution set-metadata Core --environment dev --publisher-unique-name pp','','Common output options:','  --format table|json|yaml|ndjson|markdown|raw',].join('\n') + '\n'); }

export function printSolutionPublishHelp(): void { process.stdout.write(['Usage: solution publish <uniqueName> --environment ALIAS [--wait-for-export] [--timeout-ms N] [--poll-interval-ms N] [--managed] [--out PATH] [--manifest FILE]','','Behavior:','  - Triggers Dataverse `PublishAllXml` through a first-class solution workflow instead of requiring a generic `pp dv action` call.','  - Without `--wait-for-export`, still runs one immediate export-backed sync probe and returns `readBack`, `blockers`, and `exportCheck` so the publish response itself says whether export readiness was confirmed.','  - With `--wait-for-export`, polls `pp` solution export until one export succeeds, giving a concrete post-publish synchronization checkpoint.','  - Successful `solution publish --format json` output includes a `progress` history plus `readBack` and `blockers` summaries, so machine consumers can distinguish accepted polling from a confirmed checkpoint or a timed-out export probe.','','Choose this when:','  - You need to publish remote changes and want `pp` to own both the publish action and the readiness checkpoint.','','Examples:','  pp solution publish Core --environment dev --format json','  pp solution publish Core --environment dev --wait-for-export --out ./artifacts/solutions/Core.zip --format json','','Options:','  --wait-for-export         Poll solution export until one export succeeds after publish','  --timeout-ms N            Maximum time to wait for an export checkpoint when --wait-for-export is set','  --poll-interval-ms N      Delay between export retries when --wait-for-export is set','  --managed                 Export a managed package while waiting for the checkpoint','  --out PATH                Write the export checkpoint artifact to PATH or a directory','  --manifest FILE           Write the export checkpoint manifest to FILE','','Common output options:','  --format table|json|yaml|ndjson|markdown|raw',].join('\n') + '\n'); }

export function printSolutionSyncStatusHelp(): void { process.stdout.write(['Usage: solution sync-status <uniqueName> --environment ALIAS [--skip-export-check] [--timeout-ms N] [--managed] [--out PATH] [--manifest FILE]','','Behavior:','  - Returns a first-class publish readback for the solution-scoped canvas apps, flows, and model-driven apps.','  - Returns a `blockers` list when packaged workflows are still draft or suspended, so export-readiness failures are machine-readable instead of diagnostic-only.','  - By default also runs an export probe so the result answers whether Dataverse packaging is currently exportable.','  - Use `--timeout-ms` to bound one export probe request when Dataverse export readiness stalls instead of returning promptly.','  - Streams export-probe progress to stderr and also includes a structured `progress` history in JSON/YAML output so long packaging checks remain machine-readable.','  - When no `--out` path is provided, the export probe uses a transient artifact and only returns readiness plus diagnostics.','','Choose this when:','  - You need to prove whether a solution is both published enough to inspect and stable enough to export without reissuing PublishAllXml.','','Examples:','  pp solution sync-status Core --environment dev --format json','  pp solution sync-status Core --environment dev --skip-export-check --format json','','Options:','  --skip-export-check      Skip the export probe and only return component publish readback','  --timeout-ms N           Bound one export probe request to N milliseconds','  --managed                Probe managed export readiness instead of unmanaged export readiness','  --out PATH               Write the successful export probe artifact to PATH or a directory','  --manifest FILE          Write the successful export probe manifest to FILE','','Common output options:','  --format table|json|yaml|ndjson|markdown|raw',].join('\n') + '\n'); }

export function printSolutionCheckpointHelp(): void { process.stdout.write(['Usage: solution checkpoint <uniqueName> --environment ALIAS [--out PATH] [--managed] [--manifest FILE] [--checkpoint FILE]','','Behavior:','  - Captures a rollback-oriented solution checkpoint in one command by exporting the package, preserving the release manifest, and snapshotting the current solution component inventory.','  - Writes a checkpoint document adjacent to the exported package by default, or to `--checkpoint FILE` when provided.','  - Includes a PAC-friendly organization URL hint so any downstream fallback does not need to infer it from the Dataverse API host.','','Choose this when:','  - You are about to import, promote, or patch a solution and want one durable pre-change checkpoint that is easy to compare or re-import.','','Examples:','  pp solution checkpoint Core --environment dev --out ./artifacts/checkpoints/Core-pre-import.zip --format json','  pp solution checkpoint Core --environment dev --out ./artifacts/checkpoints/ --checkpoint ./artifacts/checkpoints/Core.pp-checkpoint.json','','Options:','  --out PATH                Write the exported package to PATH or a directory','  --managed                 Export a managed package instead of the default unmanaged checkpoint','  --manifest FILE           Write the release manifest to FILE','  --checkpoint FILE         Write the composite checkpoint document to FILE','','Common output options:','  --format table|json|yaml|ndjson|markdown|raw',].join('\n') + '\n'); }

export function printSolutionComponentsHelp(): void { process.stdout.write(['Usage: solution components <uniqueName> --environment ALIAS [options]','','Behavior:','  - Lists the components currently attached to one solution in the target environment.','  - Returns stable structured rows including the component type, display name, object id, and solution metadata when available.','  - `--help` only prints this text and never validates the solution name or environment flags.','','Choose this when:','  - You need to verify what a solution contains before export, deploy, or troubleshooting.','','Examples:','  pp solution components Core --environment dev','  pp solution components Core --environment dev --format json','','Common output options:','  --format table|json|yaml|ndjson|markdown|raw',].join('\n') + '\n'); }

export function printSolutionInspectHelp(): void { process.stdout.write(['Usage: solution inspect <uniqueName> --environment ALIAS [options]','','Behavior:','  - Inspects one solution in the target environment.','  - Returns one structured record with the solution id, unique name, friendly name, version, publisher metadata, and managed state when available.','  - `--help` only prints this text and never validates the solution name or environment flags.','','Choose this when:','  - You already know the solution unique name and want metadata rather than the full inventory.','','Examples:','  pp solution inspect Core --environment dev','  pp solution inspect Core --environment dev --format json','','Common output options:','  --format table|json|yaml|ndjson|markdown|raw',].join('\n') + '\n'); }

export function printSolutionDependenciesHelp(): void { process.stdout.write(['Usage: solution dependencies <uniqueName> --environment ALIAS [--no-interactive-auth] [options]','','Behavior:','  - Lists solution dependency rows for one solution in the target environment.','  - Returns stable structured rows that identify the required and dependent components when Dataverse exposes them.','  - Classifies each missing dependency as resolved, expected external, likely import blocker, or review required.','  - `--help` only prints this text and never validates the solution name or environment flags.','','Choose this when:','  - You suspect missing prerequisites, ALM drift, or packaging/import problems.','','Examples:','  pp solution dependencies Core --environment dev','  pp solution dependencies Core --environment dev --format json','  pp solution dependencies Core --environment dev --no-interactive-auth --format json','','Options:','  --no-interactive-auth     Fail fast with structured diagnostics instead of opening browser auth','','Common output options:','  --format table|json|yaml|ndjson|markdown|raw',].join('\n') + '\n'); }

export function printSolutionCompareHelp(): void { process.stdout.write(['Usage: solution compare [uniqueName] --source-env ALIAS|--source-zip PATH|--source-folder PATH --target-env ALIAS|--target-zip PATH|--target-folder PATH [options]','','Behavior:','  - Compares source and target solution state using exactly one input per side.','  - When either side is an environment, provide the solution unique name positionally.','  - Environment-based compare defaults to a shell-only model-driven pass so drift checks return quickly and reliably.','  - Add --include-model-composition when you need model-driven artifact drift (forms, views, sitemaps) in the compare report.','','Options:','  --source-env ALIAS','  --source-zip PATH','  --source-folder PATH','  --target-env ALIAS','  --target-zip PATH','  --target-folder PATH','  --include-model-composition','  --pac PATH','  --format table|json|yaml|ndjson|markdown|raw','','Examples:','  pp solution compare Core --source-env dev --target-env prod --format json','  pp solution compare Core --source-env dev --target-env prod --include-model-composition --format json','  pp solution compare Core --source-env dev --target-zip ./artifacts/Core_managed.zip --pac /path/to/pac --format json','  pp solution compare --source-folder ./src/solutions/Core --target-zip ./artifacts/Core_managed.zip --pac /path/to/pac --format json',].join('\n') + '\n'); }

export function printSolutionExportHelp(): void { process.stdout.write(['Usage: solution export <uniqueName> --environment ALIAS [--out PATH] [--managed] [--manifest FILE] [--plan] [--dry-run] [options]','','Behavior:','  - Exports one solution package from the target environment through Dataverse.','  - `--managed` requests a managed package instead of the default unmanaged package.','  - `--out` accepts either a file path or a destination directory; omit it to use the default artifact location.','  - `--plan` and `--dry-run` return the standard non-mutating preview contract instead of exporting.','','Examples:','  pp solution export Core --environment dev --out ./artifacts/Core_unmanaged.zip --format json','  pp solution export Core --environment uat --managed --out ./artifacts/Core_managed.zip --manifest ./artifacts/Core_managed.pp-solution.json --format json','','Options:','  --out PATH','  --managed','  --manifest FILE','  --format table|json|yaml|ndjson|markdown|raw','  --plan','  --dry-run','  --yes','  --config-dir path','  --allow-interactive-auth','  --no-interactive-auth',].join('\n') + '\n'); }

export function printSolutionImportHelp(): void { process.stdout.write(['Usage: solution import <path.zip> --environment ALIAS [--overwrite-unmanaged-customizations] [--holding-solution] [--skip-product-update-dependencies] [--no-publish-workflows] [--import-job-id GUID] [--plan] [--dry-run] [options]','','Behavior:','  - Imports one solution package into the target environment through Dataverse `ImportSolution`.','  - `--plan` reads the adjacent `.pp-solution.json` release manifest when present, otherwise falls back to solution package metadata, then combines that with live target solution state so managed promotion decisions include package type, installed version, and managed/unmanaged target state.','  - `--holding-solution` is the first-class pp flag for staged managed upgrades; after the holding import, complete the platform upgrade flow before treating the promotion as finished.','  - `--dry-run` keeps the generic non-mutating preview contract and skips target-state analysis.','','Choose this when:','  - You already have a packaged solution artifact and need an environment-scoped import or promotion step.','','Choose a different path when:','  - You still need to produce the package: use `pp solution export` or `pp solution pack` first.','  - You need richer pre-import source/target drift evidence: use `pp solution compare` before importing.','','Examples:','  pp solution import ./artifacts/Core_managed.zip --environment uat --plan --format json','  pp solution import ./artifacts/Core_managed.zip --environment uat --holding-solution --format json','  pp solution import ./artifacts/Core_unmanaged.zip --environment dev --overwrite-unmanaged-customizations --format json','','Options:','  --overwrite-unmanaged-customizations   Allow the import to overwrite unmanaged customizations in the target','  --holding-solution                     Stage a managed holding import before the follow-up upgrade path','  --skip-product-update-dependencies     Skip product update dependency enforcement during import','  --no-publish-workflows                 Skip workflow publication during import','  --import-job-id GUID                   Reuse a caller-provided Dataverse import job id','  --plan                                 Print a target-aware non-mutating import plan','  --dry-run                              Print the generic non-mutating mutation preview','','Common output options:','  --format table|json|yaml|ndjson|markdown|raw',].join('\n') + '\n'); }
