import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

type FlowSupportedConnectorOperationParameterKind = 'string' | 'integer' | 'boolean' | 'record' | 'binary';
type FlowSupportedConnectorOperationParameterBucket = 'parameters' | 'queries' | 'pathParameters';

interface FlowSupportedConnectorOperationParameterSource {
  name: string;
  kind: FlowSupportedConnectorOperationParameterKind;
  bucket?: FlowSupportedConnectorOperationParameterBucket;
  buckets?: FlowSupportedConnectorOperationParameterBucket[];
  required?: boolean;
  allowPrefixedFields?: boolean;
}

interface FlowSupportedConnectorOperationSource {
  apiId: string;
  operationId: string;
  parameters: FlowSupportedConnectorOperationParameterSource[];
}

interface FlowConnectorOperationRegistrySourceDocument {
  operations: FlowSupportedConnectorOperationSource[];
}

const currentDir = dirname(fileURLToPath(import.meta.url));
const packageRoot = resolve(currentDir, '..');
const sourcePath = resolve(packageRoot, 'connector-operation-registry.source.json');
const outputPath = resolve(packageRoot, 'src', 'generated', 'connector-operation-registry.generated.ts');

function stableSortBuckets(
  buckets: FlowSupportedConnectorOperationParameterBucket[] | undefined
): FlowSupportedConnectorOperationParameterBucket[] | undefined {
  if (!buckets || buckets.length === 0) {
    return undefined;
  }

  const order: Record<FlowSupportedConnectorOperationParameterBucket, number> = {
    parameters: 0,
    queries: 1,
    pathParameters: 2,
  };

  return [...new Set(buckets)].sort((left, right) => order[left] - order[right]);
}

function normalizeDocument(
  document: FlowConnectorOperationRegistrySourceDocument
): FlowConnectorOperationRegistrySourceDocument {
  return {
    operations: document.operations
      .map((operation) => ({
        apiId: operation.apiId,
        operationId: operation.operationId,
        parameters: operation.parameters.map((parameter) => ({
          name: parameter.name,
          kind: parameter.kind,
          bucket: parameter.bucket,
          buckets: stableSortBuckets(parameter.buckets),
          required: parameter.required,
          allowPrefixedFields: parameter.allowPrefixedFields,
        })),
      }))
      .sort(
        (left, right) =>
          left.apiId.localeCompare(right.apiId) || left.operationId.localeCompare(right.operationId)
      ),
  };
}

function renderGeneratedModule(document: FlowConnectorOperationRegistrySourceDocument): string {
  const renderedDocument = JSON.stringify(
    {
      generatedAt: new Date().toISOString(),
      sourcePath: 'packages/flow/connector-operation-registry.source.json',
      operations: document.operations,
    },
    null,
    2
  );

  return `// This file is generated by packages/flow/scripts/generate-connector-operation-registry.ts.
// Do not edit it directly; update packages/flow/connector-operation-registry.source.json and rerun the generator.

import type { FlowConnectorOperationRegistryDocument } from '../connector-operation-registry';

export const FLOW_CONNECTOR_OPERATION_REGISTRY: FlowConnectorOperationRegistryDocument = ${renderedDocument};
`;
}

async function main(): Promise<void> {
  const source = JSON.parse(
    await readFile(sourcePath, 'utf8')
  ) as FlowConnectorOperationRegistrySourceDocument;
  const normalized = normalizeDocument(source);
  await writeFile(outputPath, renderGeneratedModule(normalized));
}

await main();
