import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';
import { writeFile } from 'node:fs/promises';
import { buildFlowConnectorOperationRegistryFromSources } from '../src/connector-operation-registry-ingestion';
import type { FlowConnectorOperationRegistryDocument } from '../src/connector-operation-registry';

const currentDir = dirname(fileURLToPath(import.meta.url));
const packageRoot = resolve(currentDir, '..');
const openApiManifestPath = resolve(packageRoot, 'connector-operation-openapi.source.json');
const overlayPath = resolve(packageRoot, 'connector-operation-registry.source.json');
const outputPath = resolve(packageRoot, 'src', 'generated', 'connector-operation-registry.generated.ts');

function renderGeneratedModule(document: FlowConnectorOperationRegistryDocument): string {
  const renderedDocument = JSON.stringify(
    {
      generatedAt: new Date().toISOString(),
      sourcePath: document.sourcePath,
      sourcePaths: document.sourcePaths,
      derivedOperationCount: document.derivedOperationCount,
      overlayOperationCount: document.overlayOperationCount,
      operations: document.operations,
    },
    null,
    2
  );

  return `// This file is generated by packages/flow/scripts/generate-connector-operation-registry.ts.
// Do not edit it directly; update packages/flow/connector-operation-openapi.source.json,
// packages/flow/connector-operation-registry.source.json, or the referenced connector-openapi snapshots and rerun the generator.

import type { FlowConnectorOperationRegistryDocument } from '../connector-operation-registry';

export const FLOW_CONNECTOR_OPERATION_REGISTRY: FlowConnectorOperationRegistryDocument = ${renderedDocument};
`;
}

async function main(): Promise<void> {
  const registry = await buildFlowConnectorOperationRegistryFromSources({
    packageRoot,
    manifestPath: openApiManifestPath,
    overlayPath,
  });

  await writeFile(
    outputPath,
    renderGeneratedModule({
      generatedAt: new Date().toISOString(),
      sourcePath: registry.metadata.sourcePath,
      sourcePaths: registry.metadata.sourcePaths,
      derivedOperationCount: registry.metadata.derivedOperationCount,
      overlayOperationCount: registry.metadata.overlayOperationCount,
      operations: registry.operations,
    })
  );
}

await main();
